version: "3"
volumes:
  identity-volume:
services:
  postgres:
    image: postgres:alpine
    container_name: postgres-book-store
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "BookStore@123"
  consul:
    image: consul
    container_name: consul-book-store
    environment:
      CONSUL_BIND_INTERFACE: eth0
    ports:
      - 8500:8500
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    container_name: kibana-book-store
    environment: 
      ELASTICSEARCH_HOSTS: http://elastic-search:9200
    ports: 
      - 7000:5601
    depends_on: 
      - elastic-search
  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: elastic-search-book-store
    environment: 
      - discovery.type=single-node
    ports: 
      - 7200:9200
      - 7300:9300
  identity-migrations:
    build:
      context: ./src
      dockerfile: ./IdentityServer.Migrations/Dockerfile
    container_name: identity-migrations-book-store
    environment:
      ConnectionStrings__Postgres: "Server=postgres;Database=book-store-identity-server;User Id=postgres;Password=BookStore@123;ApplicationName=IdentityMigration;"
    volumes:
      - "identity-volume:/var/output"
    entrypoint: /bin/sh -c "rm -f /var/output/migrator.txt && dockerize -wait tcp://postgres:5432 sh /docker-entrypoint.sh"
    depends_on:
      - postgres
  users:
      build:
        context: ./src
        dockerfile: ./IdentityServer.Web/Dockerfile
      container_name: identity-book-store
      entrypoint: /bin/sh -c "dockerize -wait file:///var/output/migrator.txt -timeout 100s && dockerize -wait tcp://consul:8500  -timeout 100s && dockerize -wait tcp://elastic-search:9200 -timeout 100s && dotnet /app/Users.Web.dll"
      environment:
        ASPNETCORE_ENVIRONMENT: "Development"
        ConnectionStrings__Postgres: "Server=postgres;Database=book-store-identity-server;User Id=postgres;Password=BookStore@123;ApplicationName=IdentityServer;"
        Consul__Host: "consul"
        Consul__Discovery__Hostname: "identity"
        Serilog__WriteTo__1__Args__nodeUris: http://elastic-search:9200
      ports:
        - '5110:5110'
      volumes:
        - "identity-volume:/var/output"
      depends_on:
        - postgres
        - consul
        - elastic-search
        - identity-migrations