version: "3"
volumes:
  identity-volume:
services:
  postgres:
    image: postgres:alpine
    container_name: postgres-book-store
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "BookStore@123"
  raven:
    image: ravendb/ravendb
    container_name: raven-book-store
    ports:
    - 8600:8080
    environment:
      RAVEN_ARGS: '--Setup.Mode=None'
      RAVEN_License_Eula_Accepted: 'true'
      RAVEN_Security_UnsecuredAccessAllowed: 'PrivateNetwork'
  consul:
    image: consul
    container_name: consul-book-store
    environment:
      CONSUL_BIND_INTERFACE: eth0
    ports:
      - 8500:8500
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    container_name: kibana-book-store
    environment: 
      ELASTICSEARCH_HOSTS: http://elastic-search:9200
    ports: 
      - 7000:5601
    depends_on: 
      - elastic-search
  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: elastic-search-book-store
    environment: 
      - discovery.type=single-node
    ports: 
      - 7200:9200
      - 7300:9300
  zipkin:
    image: openzipkin/zipkin
    container_name: zipink-book-store
    ports:
    - 8700:9411
    environment:
      STORAGE_TYPE: elasticsearch
      ES_HOSTS: http://elastic-search:9200
    depends_on:
      - elastic-search
  identity-migrations:
    build:
      context: ./src
      dockerfile: ./IdentityServer.Migrations/Dockerfile
    container_name: identity-migrations-book-store
    environment:
      ConnectionStrings__Postgres: "Server=postgres;Database=book-store-identity-server;User Id=postgres;Password=BookStore@123;ApplicationName=IdentityMigration;"
      ConnectionStrings__RavenDb__Urls__0: http://raven:8080
    volumes:
      - "identity-volume:/var/output"
    entrypoint: /bin/sh -c "rm -f /var/output/migrator.txt && dockerize -wait tcp://postgres:5432 -timeout 100s  && dockerize -wait tcp://raven:808 -timeout 100s  sh /docker-entrypoint.sh"
    depends_on:
      - postgres
      - raven
  identity:
      build:
        context: ./src
        dockerfile: ./IdentityServer.Web/Dockerfile
      container_name: identity-book-store
      entrypoint: /bin/sh -c "dockerize -wait file:///var/output/migrator.txt -timeout 100s && dockerize -wait tcp://consul:8500  -timeout 100s && dockerize -wait tcp://elastic-search:9200 -timeout 100s && dockerize -wait tcp://zipkin:9411 -timeout 100s && dotnet /app/IdentityServer.Web.dll"
      environment:
        ASPNETCORE_ENVIRONMENT: "Development"
        ConnectionStrings__Postgres: "Server=postgres;Database=book-store-identity-server;User Id=postgres;Password=BookStore@123;ApplicationName=IdentityServer;"
        ConnectionStrings__RavenDb__Urls__0: http://raven:8080
        Consul__Host: "consul"
        Consul__Discovery__Hostname: "identity"
        Tracing__Host: http://zipkin:9411
        Serilog__WriteTo__1__Args__nodeUris: http://elastic-search:9200
      ports:
        - '5110:5110'
      volumes:
        - "identity-volume:/var/output"
      depends_on:
        - postgres
        - consul
        - elastic-search
        - identity-migrations
        - zipkin
        - raven